### ISSUE TITLE
golang conform 

### ISSUE THREAD

**Issue by jinman0826** [ProgrammingRainbow/NvChad-2.5#1]
Automatically importing packages, and then deleting the packages in the import when saving, I think there may be a bug

**Comment by jinman0826** [comment]
The packages imported during writing are normal, but when I execute `: w `, all the imported packages are gone

**Comment by jinman0826** [comment]
1. ![image](https://github.com/user-attachments/assets/3f6e2456-802e-4182-8f6d-77d30c3455f4)
2.
![image](https://github.com/user-attachments/assets/94c14906-81d2-4e36-b5e4-3bb7d5fe51a6)

**Comment by ProgrammingRainbow** [comment]
Yeah i see what you mean. It initially is fine but if you then delete it and then try to put it back in again it start deleting it. I have no idea why but i know where it's coming from.

if you remove or comment out this it should fix it. But unneeded imports will not be automatically removed anymore.
```
        ["goimports-reviser"] = {
            prepend_args = { "-rm-unused" },
        },
```

**Comment by jinman0826** [comment]
you are right, close ` -rm-ununsed` can solve this question , maybe version cause

**Comment by 3dmario** [comment]
Problem still exists and makes the entire setup not usable.

This is my `~/.config/lua/configs/conform.lua`

```
local options = {
    formatters_by_ft = {
        lua = { "stylua" },
        go = { "gofumpt", "goimports-reviser", "golines" },
    },

    formatters = {
        ["goimports-reviser"] = {
            prepend_args = { "-rm-unused" },
        },
        golines = {
            prepend_args = { "--max-len=80" },
        },
    },

    format_on_save = {
        -- These options will be passed to conform.format()
        timeout_ms = 500,
        lsp_fallback = true,
    },
}

require("conform").setup(options)

return options
```

Once a project is initialized any new import gets automatically deleted, even if it's used in the go project. In this case my added html engine and fmt get deleted instantly when using `:w`.
```go
import (
        "fmt"
	"github.com/gofiber/fiber/v2"
        "github.com/gofiber/template/html/v2"
)
```

![image](https://github.com/user-attachments/assets/05b110c2-06e8-4a30-8e2a-1003551de73f)
